### ISSUE TITLE
Available on pkgsrc 

### ISSUE THREAD

**Issue by 0323pin** [valebes/rsClock#13]
FYI, I've packaged and merged `rsclock` into pkgsrc main branch and it's now available for NetBSD users, http://mail-index.netbsd.org/pkgsrc-changes/2022/04/08/msg251606.html

**Comment by valebes** [comment]
@0323pin Thank you very much. If you have any problems with the building of the project, feel free to contact me.

**Comment by 0323pin** [comment]
@valebes no worries, I will 😀
