### ISSUE TITLE
Error when calling cargo install

### ISSUE THREAD

**Issue by WhatzGames** [valebes/rsClock#14]
`cargo install rsclock` throws an error when using stable-x86_64-pc-windows-gnu.
unresolved import 'sys' in termion dependency

**Comment by valebes** [comment]
Hi!
So, the point is that termion, that is the crate I use to display the clock on the terminal, is currently available only for UNIX system.(See https://crates.io/crates/termion).

**Comment by WhatzGames** [comment]
That's too bad, would've loved to get a cli clock running on my machine
