### ISSUE TITLE
Screen stutters for modern GPU acceleration based terminals like Alacritty, iTerm2, etc; use redraw with NOT_VALID

### ISSUE THREAD

**Issue by poetaman** [valebes/rsClock#4]
Modern GPU based terminals draw the entire frame on redraws. The way to avoid screen from stuttering is to use a different approach to redrawing screen.

The solution is mentioned in https://github.com/neovim/neovim/issues/14225#issuecomment-809623524, and https://github.com/vim/vim/issues/8002#issuecomment-872973695.  The solution is to redraw with
NOT_VALID, which would redraw everything but not clear the screen.

This problem is similar to vim on GPU accelerated terminals also has the problem and plans to fix it: https://github.com/vim/vim/issues/8002

Here's an example of screen stuttering in rsclock. I am using tmux with frame sync feature enabled. Steps for enabling sync feature are detailed here: https://github.com/alacritty/alacritty/issues/4904#issuecomment-872614318

You won't see this problem with traditional terminals that do not use GPU acceleration. Though the future is with terminals that use GPU acceleration -- they are fast.

https://user-images.githubusercontent.com/71736629/127050251-3fa40991-d800-4083-84f1-94fad811c2c0.mp4

> As a sidenote, this screen stuttering does not happen in tty-clock (I tried with same setup & within tmux). But it doesn't guarantee all clock instances to update at same time like rsClock seems to (https://github.com/xorg62/tty-clock/issues/70). Great work rsClock on that front!

**Comment by valebes** [comment]
Thanks @reportaman  for the documentation provided. 
As soon as I have time I will read the whole thing.
Thanks for the contribution :-) .

**Comment by valebes** [comment]
Yeah, I can reproduce the issue on Alacritty

**Comment by poetaman** [comment]
Yes I think this particular quirk of transitioning from coding TUIs that work on old terminal drawing mechanisms to ones that work on both new & old deserves an article on forums like reddit, medium, and hacker news... Given vim too has this problem (neovim doesn't though), shows that even experienced programmers are unaware. Anyway, I am happy to know you could reproduce it.

**Comment by valebes** [comment]
@reportaman Hi, try to check the latest commit. If is all okay I will proceed to release a new release.

**Comment by poetaman** [comment]
@valebes Yes, its working well now! No more stutters!!

Here's a video:

https://user-images.githubusercontent.com/71736629/128223179-f467c2c7-9d10-429e-ad81-d53a3e7f0231.mp4
