### ISSUE TITLE
Option to disable foreground/background layer?

### ISSUE THREAD

**Issue by poetaman** [valebes/rsClock#7]
It would be nice to be able to disable foreground/background layers independently or perhaps make them transparent to reveal only one.

![Screen Shot 2021-08-04 at 10 58 08 AM](https://user-images.githubusercontent.com/71736629/128230972-5368a84d-f00d-40d3-8b23-b34ec1e8256a.png)

**Comment by reportaman** [comment]
Oh I think I get it... there are two layers? Is there a way to suppress foreground layer? To make it not draw or make it completely transparent?
